/**
 * db.ts — singleton SQLite connection (server-only)
 *
 * Reads from data/archive.db, which is generated by scripts/export_sqlite.py
 * from the master DuckDB bill_artifacts.db source.
 */
import path from "path";
import Database from "better-sqlite3";

let _db: Database.Database | null = null;

export function getDb(): Database.Database {
  if (!_db) {
    const dbPath = path.resolve(process.cwd(), "../../data/archive.db");
    _db = new Database(dbPath, { readonly: true, fileMustExist: true });
    _db.pragma("journal_mode = WAL");
  }
  return _db;
}
